[project]
name = "auto-vllm-node"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "flashinfer-cubin==0.6.14",
    "flashinfer-python==0.6.14",
    "vllm==0.26.0",
]

[tool.uv]
package = false
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64' and implementation_name == 'cpython'",
]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64' and implementation_name == 'cpython'",
]

[[tool.uv.index]]
name = "flashinfer"
url = "https://flashinfer.ai/whl"
explicit = true

[tool.uv.sources]
flashinfer-cubin = { index = "flashinfer" }
